CREATE PROCEDURE spAsignarSensor
	@CriaID int
AS

	BEGIN TRY
		BEGIN TRAN

		INSERT INTO Sensores
		VALUES (@CriaID)

		DECLARE @SensorID int = (SELECT SensorID FROM Sensores WHERE CriaID = @CriaID)

		UPDATE Crias
		SET SensorID = @SensorID
		WHERE CriaID = @CriaID

		COMMIT TRAN

	END TRY
	BEGIN CATCH

		IF @@TRANCOUNT > 0 
		ROLLBACK TRANSACTION

	END CATCH